"""A second way in: ``python -m forecast_lab.interfaces <command>``.

Equivalent to the ``forecast-lab`` console script in every respect, and it exists because
that script is a generated ``.exe`` shim on Windows - a freshly built binary with no
reputation, which Windows Smart App Control refuses to launch at all:

    error: Failed to spawn: `forecast-lab`
    Caused by: an application control policy blocked this file (os error 4551)

Measured on this project: the shim in a long-installed environment runs fine, while the
one regenerated by `uv sync` minutes earlier stays blocked across repeated attempts. The
extensions inside site-packages clear within a run or two as SAC evaluates them one at a
time; the launcher shim is slower and there is no way to know how much slower.

Going through the interpreter sidesteps the shim entirely, because `python` is already a
trusted binary. It costs three lines and removes a class of failure that looks like a
broken install and is not.
"""

from forecast_lab.interfaces.cli import app

if __name__ == "__main__":
    app()
